{
  "contest": 142,
  "handle": "cryptphi",
  "address": "0x876133657f5356e376b7ae27d251444727ce9488",
  "risk": "2",
  "title": "Same order could be exercised multiple times if transferFrom fails",
  "issueId": 367,
  "issueUrl": "https://github.com/code-423n4/2022-06-putty-findings/issues/367"
}